export const PAY_FEE_FORM_FIELDS = [
  {
    label: 'First Name',
    value: '',
    required: true,
    name: 'firstName',
    placeholder: 'Enter your first name',
    type: 'text',
    size: 'col-6',
  },
  {
    label: 'Last Name',
    value: '',
    required: true,
    name: 'lastName',
    placeholder: 'Enter your last name',
    type: 'text',
    size: 'col-6',
  },
  {
    label: 'Email Address',
    value: '',
    required: true,
    name: 'email',
    placeholder: 'Enter your email address',
    type: 'text',
    size: 'col-6',
  },
  {
    label: 'Phone Number',
    value: '',
    required: true,
    name: 'phoneNumber',
    placeholder: '_ _ _ - _ _ _ - _ _ _ _',
    type: 'text',
    size: 'col-6',
  },
  {
    label: 'Street Address Line 1',
    subLabel: '',
    value: '',
    required: true,
    name: 'addressLine1',
    placeholder: 'Enter your full address',
    type: 'text',
    size: 'col-6',
  },
  {
    label: 'Suite/Floor/Apt',
    subLabel: '',
    value: '',
    required: false,
    name: 'addressLine2',
    placeholder: 'ex. Suite 3',
    type: 'text',
    size: 'col-6',
  },
  {
    label: 'City',
    subLabel: '',
    value: '',
    required: true,
    name: 'city',
    placeholder: 'Enter your city',
    type: 'text',
    size: 'col-4',
  },
  {
    label: 'State',
    subLabel: '',
    value: '',
    required: true,
    name: 'state',
    placeholder: 'Choose your state',
    type: 'select',
    size: 'col-4',
    options: [],
  },
  {
    label: 'Zipcode',
    subLabel: '',
    value: '',
    required: true,
    name: 'zipCode',
    placeholder: 'Enter your zip code',
    type: 'text',
    size: 'col-4',
  },
  {
    label: 'Invoice Number',
    subLabel: 'Select an invoice to pay',
    value: '',
    required: true,
    name: 'invoiceNumber',
    type: 'text',
    size: 'col-6',
    disabled: true,
  },
  {
    label: 'Amount',
    subLabel: '',
    value: '',
    required: true,
    name: 'amount',
    type: 'text',
    size: 'col-6',
    disabled: true,
  },
];
