/**
#############################################################################
WARNING GENERATED CODE DO NOT MODIFY -

All client side API services are generated by the server side API
developer when the API is created. Please do not make changes to this file

############################################################################
**/

// TODO - Added a null type on these to smooth interactions if the value is null at any point
export interface IAppUserReadOnlyModel {
  userId: number;
  fullName: string;
  userName: string;
  emailAddress: string;
  resetRequired: boolean;
  lastLoginDateUtc: string | null;
}
