/**
#############################################################################
WARNING GENERATED CODE DO NOT MODIFY - 

All client side API services are generated by the server side API 
developer when the API is created. Please do not make changes to this file

############################################################################
**/
export interface IUserProfileModel {
    userProfileId: number;
    userId: number;
    firstName: string;
    middleName: string;
    lastName: string;
    suffix: string;
    displayName: string;
    officePhoneNumber: string;
    mobilePhoneNumber: string;
    birthCity: string;
    birthState: string;
    birthCountry: string;
    countryCitizenship: string;
    absId: string;
    certificationStatus: string;
    nPI: string;
    genderId: number;
    birthDate: Date;
    race: string;
    ethnicity: string;
    firstLanguageId: number;
    bestLanguageId: number;
    receiveComms: boolean;
    userConfirmed: boolean;
    userConfirmedDate: Date;
    createdByUserId: number;
    createdAtUtc: Date;
    lastUpdatedAtUtc: Date;
    lastUpdatedByUserId: number;
    street1: string;
    street2: string;
    city: string;
    state: string;
    zipCode: string;
    country: string;
}
