/**
#############################################################################
WARNING GENERATED CODE DO NOT MODIFY - 

All client side API services are generated by the server side API 
developer when the API is created. Please do not make changes to this file

############################################################################
**/
export interface IUserProfileModel
{
  userProfileId: number;
  userId: number;
  firstName: string;
  middleName: string;
  lastName: string;
  suffix: string;
  displayName: string;
  officePhoneNumber: string;
  mobilePhoneNumber: string;
  birthCity: string;
  birthState: string;
  birthCountry: string;
  countryCitizenship: string;
  aBSId: number;
  certificationStatusId: number;
  nPI: string;
  gender: string;
  birthDate: string;
  race: string;
  ethnicity: string;
  firstLanguage: string;
  bestLanguage: string;
  receiveComms: boolean;
  userConfirmed: boolean;
  userConfirmedDate: string;
  createdByUserId: number;
  createdAtUtc: string;
  lastUpdatedAtUtc: string;
  lastUpdatedByUserId: number;
}
