CREATE TABLE [dbo].[AppRefLet_hist] (
    [id]                      NUMERIC (18)          NOT NULL,
    [created]                 DATETIME              NULL,
    [creator]                 CHAR (3)              NULL,
    [modified]                DATETIME              NULL,
    [modifier]                [dbo].[modifier]      NULL,
    [modifications]           [dbo].[modifications] NOT NULL,
    [UserId]                  INT                   NULL,
    [candidate]               CHAR (6)              NOT NULL,
    [exam_type]               VARCHAR (8)           NOT NULL,
    [let_type]                TINYINT               NOT NULL,
    [alternaterole]           VARCHAR (200)         NULL,
    [explain]                 VARCHAR (8000)        NULL,
    [official]                VARCHAR (85)          NULL,
    [coordinator]             VARCHAR (85)          NULL,
    [title]                   VARCHAR (50)          NULL,
    [address]                 VARCHAR (200)         NULL,
    [city]                    VARCHAR (30)          NULL,
    [state]                   VARCHAR (2)           NULL,
    [zip]                     VARCHAR (10)          NULL,
    [email]                   VARCHAR (100)         NULL,
    [coordinator_email]       VARCHAR (100)         NULL,
    [phone]                   VARCHAR (100)         NULL,
    [hosp]                    VARCHAR (356)         NULL,
    [let_rcvd]                DATETIME              NULL,
    [coordinator_rcvd]        DATETIME              NULL,
    [response_ip]             VARCHAR (15)          NULL,
    [let_sent]                DATETIME              NULL,
    [let_approve]             DATETIME              NULL,
    [sameinstitution]         VARCHAR (5)           NULL,
    [fullprivileges]          VARCHAR (5)           NULL,
    [professionalinteraction] VARCHAR (5)           NULL,
    [personalrelationship]    VARCHAR (5)           NULL,
    [acceptableskills]        VARCHAR (5)           NULL,
    [dependable]              VARCHAR (5)           NULL,
    [communicationskills]     VARCHAR (5)           NULL,
    [behavior]                VARCHAR (5)           NULL,
    [participatesactivities]  VARCHAR (5)           NULL,
    [substanceabuse]          VARCHAR (5)           NULL,
    [disciplinaryactions]     VARCHAR (5)           NULL,
    [recommend]               VARCHAR (5)           NULL,
    [pd_completedres]         VARCHAR (5)           NULL,
    [pd_sixoperative]         VARCHAR (5)           NULL,
    [pd_sixclinical]          VARCHAR (5)           NULL,
    [pd_endoscopy]            VARCHAR (5)           NULL,
    [scope]                   VARCHAR (5)           NULL,
    [remarks]                 VARCHAR (8000)        NULL,
    [signature]               VARCHAR (5)           NULL,
    [coordinator_signature]   VARCHAR (5)           NULL,
    [pd_confirm]              VARCHAR (5)           NULL,
    [coordinator_confirm]     VARCHAR (5)           NULL,
    [sec_order]               TINYINT               NULL,
    [id_code]                 VARCHAR (100)         NULL,
    [adversecount]            TINYINT               NULL,
    [pd_chiefweeks] varchar (5) NULL,
	[pd_pg4chieflet] varchar (5) NULL,
	[pd_reqhours] varchar (5) NULL,
	[pd_extension] varchar (5) NULL,
	[pd_flexrots] varchar (5) NULL,
	[pd_introts] varchar (5) NULL,
	[pd_research] varchar (5) NULL,
	[pd_reqweeks] varchar (5) NULL,
    [pd_documents]            VARCHAR (5)           NULL
);

