CREATE TABLE [dbo].[exam_score_hist] (
    [id]                  NUMERIC (18)   NULL,
    [created]             DATE           NULL,
    [creator]             CHAR (3)       NULL,
    [modified]            DATE           NULL,
    [modifier]            CHAR (3)       NULL,
    [modifications]       SMALLINT       NULL,
    [exam_id]             NUMERIC (18)   NULL,
    [examiner_userid]     INT            NULL,
    [examiner]            CHAR (6)       NULL,
    [role]                CHAR (2)       NULL,
    [score]               NUMERIC (9, 3) NULL,
    [score_adjusted]      NUMERIC (9, 3) NULL,
    [case_1]              VARCHAR (6)    NULL,
    [case_1_score]        NUMERIC (9, 3) NULL,
    [comment_1]           VARCHAR (MAX)  NULL,
    [critical_fail_1]     BIT            NULL,
    [case_2]              VARCHAR (6)    NULL,
    [case_2_score]        NUMERIC (9, 3) NULL,
    [comment_2]           VARCHAR (MAX)  NULL,
    [critical_fail_2]     BIT            NULL,
    [case_3]              VARCHAR (6)    NULL,
    [case_3_score]        NUMERIC (9, 3) NULL,
    [comment_3]           VARCHAR (MAX)  NULL,
    [critical_fail_3]     BIT            NULL,
    [case_4]              VARCHAR (6)    NULL,
    [case_4_score]        NUMERIC (9, 3) NULL,
    [comment_4]           VARCHAR (MAX)  NULL,
    [critical_fail_4]     BIT            NULL,
    [cmp_num_case_scores] TINYINT        NULL,
    [cmp_num_cases]       TINYINT        NULL,
    [override_reason]     VARCHAR (1000) NULL,
    [override_ip]         VARCHAR (15)   NULL
);

