CREATE TABLE [dbo].[moc_eligibility_hist] (
    [UserId]                   INT            NULL,
    [candidate]                CHAR (6)       NOT NULL,
    [created]                  DATETIME       NOT NULL,
    [creator]                  CHAR (3)       NOT NULL,
    [modified]                 DATETIME       NULL,
    [modifier]                 CHAR (3)       NULL,
    [cohort]                   SMALLINT       NULL,
    [examcode]                 VARCHAR (7)    NULL,
    [seniority_date]           DATETIME       NULL,
    [cmoc_cohort]              SMALLINT       NULL,
    [cmoc_examcode]            VARCHAR (7)    NULL,
    [cmoc_seniority_date]      DATETIME       NULL,
    [optout]                   DATETIME       NULL,
    [current_cycle]            INT            NULL,
    [current_cycle_year]       INT            NULL,
    [current_year]             INT            NULL,
    [current_trackcode]        VARCHAR (32)   NULL,
    [current_cycle_due]        DATETIME       NULL,
    [next_reporting_due]       DATETIME       NULL,
    [extension_due]            DATETIME       NULL,
    [num_cycles_non_compliant] TINYINT        NOT NULL,
    [note]                     VARCHAR (1000) NULL,
    [req_cme_1]                INT            NULL,
    [req_cme_1_sa]             INT            NULL,
    [req_cme_tot]              INT            NULL,
    [cme_from]                 DATETIME       NULL,
    [cme_to]                   DATETIME       CONSTRAINT [DF_moc_eligibility_hist_cme_to] DEFAULT ((0)) NULL
);

