export const ADD_PROGRAM_DIRECTOR_FIELDS = [
  {
    label: 'Program Director',
    value: '',
    required: true,
    name: 'programDirector',
    placeholder: 'Enter Program Director’s name',
    type: 'text',
    size: 'col-6',
  },
  {
    label: 'Title',
    subLabel: '',
    value: '',
    required: true,
    name: 'title',
    placeholder: 'Enter their Title',
    type: 'text',
    size: 'col-6',
  },
  {
    label: 'Program Name',
    subLabel: '',
    value: '',
    required: true,
    name: 'programName',
    placeholder: 'Enter Program Name',
    type: 'text',
    size: 'col-12',
  },
  {
    label: 'Program Director’s Email Address',
    subLabel: '',
    value: '',
    required: true,
    name: 'email',
    placeholder: 'Enter Program Director’s email address',
    type: 'email',
    size: 'col-6',
  },
  {
    label: 'Confirm Email Address',
    subLabel: '',
    value: '',
    required: true,
    name: 'confirmEmail',
    placeholder: 'Enter Program Director’s email address again',
    type: 'email',
    size: 'col-6',
  },
];
