import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';

import { IProgramReadOnlyModel } from '../../models/trainees/program-read-only.model';

/**
#############################################################################
WARNING GENERATED CODE DO NOT MODIFY - 

All client side API services are generated by the server side API 
developer when the API is created. Please do not make changes to this file

############################################################################
**/

@Injectable({
  providedIn: 'root',
})
export class ProgramsService {
    private readonly baseEndpoint = 'api/trainees/programs';

    constructor(private httpClient: HttpClient) {}

 
        public retrieveProgramReadOnly_GetByUserId(userId: number,
        apiVersion = '1.0'): Observable<IProgramReadOnlyModel> {
            /**
            * Claims
            */
            
            /**
            * Business Rules
            * No business rules exist for this model
            */
            
            /**
            * Required Parameters
            * userId:Number
            * apiVersion
            */
            
            /**
            * Calls Sp(s)
            * [get_user_programs]
            */
            
            
            return this.httpClient.get<IProgramReadOnlyModel>(`${this.baseEndpoint}/?api-version=${apiVersion}&userId=${userId}`);
        }


}
