export const ADD_REFERENCE_LETTER_FIELDS = [
  {
    label: 'Name of Authenticating Official',
    subLabel: '(Must be a Physician)',
    value: '',
    required: true,
    name: 'official',
    placeholder: 'Enter Official’s name',
    type: 'text',
    size: 'col-6',
  },
  {
    label: "Authenticating Official'/s Role",
    subLabel: '',
    value: '',
    required: true,
    name: 'roleId',
    placeholder: 'Choose their role',
    type: 'select',
    size: 'col-6',
    options: [],
  },
  {
    label: 'Alternate Role Role',
    subLabel: '',
    value: '',
    required: false,
    name: 'altRoleId',
    placeholder: 'Choose their role',
    type: 'select',
    size: 'col-6',
    hidden: true,
    options: [],
  },
  {
    label: 'Reason for Alternate Official',
    subLabel: '',
    value: '',
    required: false,
    name: 'explain',
    placeholder: 'Enter a reason',
    type: 'select',
    size: 'col-6',
    hidden: true,
    options: [],
  },
  {
    label: 'Authenticating Official’s Title',
    subLabel: '',
    value: '',
    required: false,
    name: 'title',
    placeholder: 'Enter Official’s title',
    type: 'text',
    size: 'col-12',
  },
  {
    label: 'Authenticating Official’s Email Address',
    subLabel: '',
    value: '',
    required: true,
    name: 'email',
    placeholder: 'Enter Official’s email address',
    type: 'email',
    size: 'col-4',
  },
  {
    label: 'Confirm Email Address',
    subLabel: '',
    value: '',
    required: true,
    name: 'confirmEmail',
    placeholder: 'Enter Official’s email address again',
    type: 'email',
    size: 'col-4',
  },
  {
    label: 'Authenticating Official’s Phone Number',
    subLabel: '',
    value: '',
    required: true,
    name: 'phone',
    placeholder: '(999) 999-9999',
    type: 'tel',
    size: 'col-4',
  },
  {
    label: 'Name of Affiliated Institution',
    subLabel: '',
    value: '',
    required: false,
    name: 'hosp',
    placeholder: 'Enter affiliated institution',
    type: 'text',
    size: 'col-12',
  },
  {
    label: 'City',
    subLabel: '',
    value: '',
    required: true,
    name: 'city',
    placeholder: 'Enter your city',
    type: 'text',
    size: 'col-4',
  },
  {
    label: 'State',
    subLabel: '',
    value: '',
    required: true,
    name: 'state',
    placeholder: 'Choose your state',
    type: 'select',
    size: 'col-4',
    options: [],
  },
  {
    label: 'Name',
    subLabel: '',
    value: '',
    required: true,
    name: 'fullName',
    placeholder: 'Enter your full name',
    type: 'text',
    size: 'col-12',
  },
];
