CREATE proc [dbo].[ins_program]
        @number char ( 4 ) output,
        @exam exam,
        @name1 varchar (  35 )  ,
        @name2 varchar (  35 )  ,
        @abbname varchar (  25 )  ,
        @pd varchar (  42 )  ,   
        @last varchar (  17 )  ,   
        @l1 smallint  ,   
        @l2 smallint  ,   
        @l3 smallint  ,   
        @l4 smallint  ,   
        @l5 smallint  ,   
        @l6 smallint  ,   
        @total smallint  ,   
        @approval char ( 1 ),   
        @effdate smalldatetime ,    
        --@booksord int  ,   
        @booksent int  ,   
        @paid char ( 1 ) ,   
        @invoice char ( 1 ),   
        @pdate smalldatetime ,    
        @pdate1 smalldatetime ,    
        @pdate2 smalldatetime ,    
        @pdate3 smalldatetime ,    
        @pdate4 smalldatetime ,    
        --@amt money  ,   
        @amt1 money  ,   
        @amt2 money  ,   
        @amt3 money  ,   
        @amt4 money  ,   
        @designee char ( 1 ) ,   
        @invsent char ( 1 )  ,   
        @po varchar (  15 )  ,   
        @po1 varchar (  10 )  ,   
        @po2 varchar (  10 )  ,   
        @po3 varchar (  10 )  ,   
        @po4 varchar (  10 )  ,   
        @altname varchar (  35 )  ,   
        @note varchar (  255 ),    
        --@amtperbook money,       
        @designeename varchar (35 ),
        @sdate smalldatetime,
        @RRC_ID varchar(10)	=null,
        @RRC_TYPE char(1)	=null,
        @junior int=0,
        @senior int=0
as
	if exists(SELECT number FROM Program WHERE number=@number and exam=@exam) and rtrim(@number)!=''
	begin
		update program set 
			name1		=@name1,
			name2		=@name2,
			abbname		=@abbname,
			pd		=@pd,
			last		=@last,
			l1		=@l1,
			l2		=@l2,
			l3		=@l3,
			l4		=@l4,
			l5		=@l5,
			l6		=@l6,
			total		=@total,
			approval	=@approval,
			effdate		=@effdate,
			--booksord 	=@booksord,
			booksent	=@booksent,
			paid 		=@paid,
			invoice 	=@invoice,
			pdate 		=@pdate,
			--amt		=@amt,
			designee 	=@designee,
			invsent 	=@invsent,
			po  		=@po,
			altname 	=@altname,
			note  		=@note,
			modified 	=getdate(),
			--amtperbook  	=@amtperbook,
			designeename	=@designeename,
			sdate 		=@sdate,
			pdate1		=@pdate1,
			pdate2		=@pdate2,
			pdate3		=@pdate3,
			pdate4 		=@pdate4,
			amt1		=@amt1,
			amt2		=@amt2,
			amt3 		=@amt3,
			amt4 		=@amt4,
			po1 		=@po1,
			po2		=@po2,
			po3 		=@po3,
			po4		=@po4 ,
			RRC_ID	=@RRC_ID,
			RRC_TYPE	=@RRC_TYPE,
			junior		=@junior,
			senior		=@senior 
		where number = @number and exam=@exam
	end
	else
	begin
		if rtrim(isnull(@number,''))=''		
		begin	
			select @number = dbo.udf_get_program_id()
		end
		insert program (number, exam, name1, name2, abbname, pd, last,
			l1, l2, l3, l4, l5, l6, total, approval, effdate,
			booksent, paid, invoice, pdate,
			designee, invsent, po, altname, note,  modified,
			designeename,sdate,
			pdate1,pdate2,pdate3,pdate4,
			amt1,amt2,amt3,amt4,
			po1,po2,po3,po4,RRC_ID,RRC_TYPE,junior,senior )
		values (@number, @exam, @name1, @name2, @abbname, @pd, @last,
			@l1, @l2, @l3, @l4, @l5, @l6, @total, @approval, @effdate,
			@booksent, @paid, @invoice, @pdate,
			@designee, @invsent, @po, @altname, @note, getdate(),
			@designeename,@sdate,
			@pdate1,@pdate2,@pdate3,@pdate4,
			@amt1,@amt2,@amt3,@amt4,
			@po1,@po2,@po3,@po4,@RRC_ID,@RRC_TYPE,@junior,@senior)
	end
	select @number