CREATE PROCEDURE [dbo].[insert_outcome_registries]
    @UserId INT,
    @SurgeonSpecificRegistry VARCHAR(8000)=NULL,
    @RegistryComments VARCHAR(8000)=NULL,
    @RegisteredWithACHQC BIT,
    @RegisteredWithCESQIP BIT,
    @RegisteredWithMBSAQIP BIT,
    @RegisteredWithABA BIT,
    @RegisteredWithASBS BIT,
    @RegisteredWithMSQC BIT,
    @RegisteredWithABMS BIT,
    @RegisteredWithNCDB BIT,
    @RegisteredWithRQRS BIT,
    @RegisteredWithNSQIP BIT,
    @RegisteredWithNTDB BIT,
    @RegisteredWithSTS  BIT,
    @RegisteredWithTQIP BIT,
    @RegisteredWithUNOS BIT,
    @RegisteredWithNCDR BIT,
    @RegisteredWithSVS BIT,
    @RegisteredWithELSO BIT,
    @RegisteredWithSSR BIT,
    @UserConfirmed BIT =NULL,
    @UserConfirmedDateUtc DATETIME= NULL,
    @LastUpdatedByUserId INT,
    @CreatedByUserId INT
AS
	SET NOCOUNT ON

	INSERT INTO [dbo].[outcome_registries] (UserId, SurgeonSpecificRegistry,RegistryComments, RegisteredWithACHQC, RegisteredWithCESQIP, RegisteredWithMBSAQIP, RegisteredWithABA,
                               RegisteredWithASBS, RegisteredWithMSQC, RegisteredWithABMS, RegisteredWithNCDB, RegisteredWithRQRS,
                               RegisteredWithNSQIP, RegisteredWithNTDB, RegisteredWithSTS, RegisteredWithTQIP, RegisteredWithUNOS, RegisteredWithNCDR,
                               RegisteredWithSVS, RegisteredWithELSO,RegisteredWithSSR,UserConfirmed,UserConfirmedDateUtc, CreatedByUserId, LastUpdatedByUserId)
	VALUES (
	         @UserId,
	         @SurgeonSpecificRegistry,
	         @RegistryComments,
			 @RegisteredWithACHQC,
			 @RegisteredWithCESQIP,
			 @RegisteredWithMBSAQIP,
			 @RegisteredWithABA,
			 @RegisteredWithASBS,
			 @RegisteredWithMSQC,
			 @RegisteredWithABMS,
			 @RegisteredWithNCDB,
			 @RegisteredWithRQRS,
			 @RegisteredWithNSQIP,
			 @RegisteredWithNTDB,
			 @RegisteredWithSTS,
			 @RegisteredWithTQIP,
			 @RegisteredWithUNOS,
			 @RegisteredWithNCDR,
			 @RegisteredWithSVS,
			 @RegisteredWithELSO,
			 @RegisteredWithSSR,
			 @UserConfirmed,
			 @UserConfirmedDateUtc,
	         @CreatedByUserId,
	         @LastUpdatedByUserId
		   )
EXEC get_outcome_registries @UserId