export const GRID_DEFAULT_DATA = [
  {
    name: 'Daniel Sarria',
    title: 'Software Engineer',
    date: new Date('12-25-2024'),
    status: 'Requested',
    expandedRowContent: 'This is the expanded row content',
    expanded: false,
  },
  {
    name: 'Joe Mayberry',
    title: 'Software Engineer',
    date: new Date('04-01-2024'),
    status: 'Approved',
    expandedRowContent: 'This is the expanded row content',
    expanded: false,
  },
  {
    name: 'Alan Bryant',
    title: 'Software Architect',
    date: new Date('01-01-2022'),
    status: 'Failed',
    expandedRowContent: 'This is the expanded row content',
    expanded: false,
  },
  {
    name: 'Tim Yocum',
    title: 'CEO',
    date: new Date('01-01-2022'),
    status: 'Approved',
    expandedRowContent: 'This is the expanded row content',
    expanded: false,
  },
  {
    name: 'Test User',
    title: 'Green Horn',
    date: new Date('01-01-2022'),
    status: 'Failed',
    expandedRowContent: 'This is the expanded row content',
    expanded: false,
  },
  {
    name: 'Test User 2',
    title: 'Senior Green Horn',
    date: new Date('01-01-2022'),
    status: 'Failed',
    expandedRowContent: 'This is the expanded row content',
    expanded: false,
  },
];
