INSERT INTO trainingtype (TrainingType)
VALUES ('Acute Care Surgery'),
('Advanced GI Surgery'),
('Bariatric Surgery'),
('Breast Surgery'),
('Burns'),
('Colon and Rectal Surgery'),
('Complex General Surgical Oncology'),
('Critical Care'),
('Endocrine Surgery'),
('Endoscopy'),
('Hand Surgery'),
('Hepatobiliary Surgery'),
('Minimally Invasive Surgery'),
('Pediatric Surgery'),
('Plastic Surgery'),
('Thoracic Surgery'),
('Transplantation'),
('Trauma'),
('Vascular Surgery'),
('Other (specify)')