INSERT INTO attestations_text (ExamTypeId, ExamSpecialtyId, AttestationText, CreatedByUserId, LastUpdatedByUserId)
VALUES (5, 1, '<p>Carefully review the <bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold> below.  Check the box that appears beneath your name if you agree with each of the statements.  This will serve as your electronic signature.</p>
		<p>Exam registration may be permitted pending the formal ABS review and approval of your electronically submitted application materials. The ABS reserves the right to cancel your registration and your scheduled examination center appointment should your submitted application materials not meet application requirements.</p>
		<p>Your Program Director will be contacted separately to attest to your clinical skills.  Approval of your application is contingent upon receipt of your program director''s attestation.</p>
		<br/>
		<p><bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold></p>
				<ol>
					<li>I hereby make request to The American Board of Surgery, Inc. (ABS) to enter the evaluation and examination process leading to certification or Continuous Certification in surgery, vascular surgery, pediatric surgery, surgical critical care, complex general surgical oncology, or surgery of the hand, as applicable, all in accordance with and subject to ABS bylaws and policies.  I agree that in this process the ABS may investigate my surgical performance, knowledge, professionalism, and my standing and reputation as a physician, including my compliance with the standards and ethics of the profession.  I understand and agree that:
						<p>
							<p><nbsp/> <nbsp/>a. the submission of any falsified documents or information to the ABS; or</p>
							<p><nbsp/> <nbsp/>b. the use of any falsified ABS documents or the submission of any such documents to other persons; or</p>
							<p><nbsp/> <nbsp/>c. the giving or receiving of aid in the examination as evidenced either by observation at the time of the examination or by analysis of my answers and those or one or more other participants in that examination; or</p>
							<p><nbsp/> <nbsp/>d. the unauthorized possession, reproduction, or disclosure of any material, including but not limited to examination questions or answers before, during, or after the examination; or</p>
							<p><nbsp/> <nbsp/>e. the offer of any financial or other benefit to any director, officer, employee, proctor, or other agent or representative of the ABS in return for any right, privilege or benefit which is not usually granted by the ABS to other similarly situated candidates or persons,</p>
						</p>
					may be sufficient cause for the ABS to bar me permanently from all future examinations, to terminate my participation in the examination, to invalidate the results of my examination, to withhold my scores or certificate, to revoke my certificate, or to take other appropriate action.</li>
					<li>I hereby authorize any hospital or medical staff where I now have, have had, or have applied for medical staff privileges, and any medical organization of which I am a member or to which I have applied for membership, and any person who may have information (including medical records, patient records, and reports of committees) which is deemed by ABS to be material to its evaluation of this application, to provide such information to representatives of the ABS.  I agree that communications of any nature made to the ABS regarding this application may be made in confidence and shall not be made available to me under any circumstances.  I hereby release from liability any hospital, medical staff, medical organization or person, and ABS and its representatives, for acts performed in connection with this application.</li>
					<li>I hereby agree to indemnify ABS, its members, examiners, officers, employees, or other agents or representatives, or any  hospital, medical staff, medical organization or person that provides information pursuant to this application and hold them harmless from any and all claims, losses, liabilities, expenses, lawsuits and damages (including attorneys'' fees, costs and expenses) arising out of any action the ABS or any of its agents or representatives may take in regard to this application.</li>
					<li>I hereby consent to submit to the exclusive jurisdiction of the courts of Philadelphia County, Pennsylvania for any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification, and agree not to commence any action, suit or proceeding relating thereto except in such courts.  I hereby agree that any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification shall be governed by the laws of the Commonwealth of Pennsylvania.</li>
					<li>I understand my certificate will be valid on the condition that I meet the requirements of the ABS Continuous Certification Program, which may be modified at the sole discretion of the ABS, and which include successful completion of periodic assessments, as well as participation in continuing medical education and practice improvement activities. I recognize that not meeting these requirements at any time may result in the public reporting of my failure to meet current ABS Continuous Certification requirements and may also result in suspension or revocation  of my certificate.</li>
					<li>I understand and agree that if I am certified, the ABS will send biographical and demographic data about me to the American Board of Medical Specialties (ABMS), which will contact me directly regarding the publication of my information in the ABMS Directory of Board Certified Medical Specialists.</li>
					<li>I understand and agree that the ABS may inform the director of the program in which I complete my chief resident year or other special requirements of the ABS as to my performance on any or all of the ABS'' examinations taken by me up to the point of certification.</li>
					<li>I understand and agree that the ABS, given its obligation to the public, may disclose to third parties, including medical licensing authorities, otherwise confidential information about me whenever in its sole judgment it has determined my conduct to be unethical or unprofessional.</li>
					<li>I consent and give permission to the ABS to use in de-identified format any data I submit as part of the ABS examination process (including data derived from my application, practice profile or examination results) for evaluation and research purposes authorized by the ABS.</li>
					<li>I am in good ethical standing in my community. I hereby pledge myself to the highest standards in the practice of surgery. If I am certified and these statements are shown to be false, I agree to surrender my certificate.</li>
				</ol>', 6, 6),
                (5,2,'	<p>Carefully review the <bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold> below.  Check the box that appears beneath your name if you agree with each of the statements.  This will serve as your electronic signature.</p>
		<p>Exam registration may be permitted pending the formal ABS review and approval of your electronically submitted application materials. The ABS reserves the right to cancel your registration and your scheduled examination center appointment should your submitted application materials not meet application requirements.</p>
		<p>Your Program Director will be contacted separately to attest to your clinical skills.  Approval of your application is contingent upon receipt of your program director''s attestation.</p>
		<br/>
		<p><bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold></p>
				<ol>
					<li>I hereby make request to The American Board of Surgery, Inc. (ABS) to enter the evaluation and examination process leading to certification or Continuous Certification in surgery, vascular surgery, pediatric surgery, surgical critical care, complex general surgical oncology, or surgery of the hand, as applicable, all in accordance with and subject to ABS bylaws and policies.  I agree that in this process the ABS may investigate my surgical performance, knowledge, professionalism, and my standing and reputation as a physician, including my compliance with the standards and ethics of the profession.  I understand and agree that:
						<p>
							<p><nbsp/> <nbsp/>a. the submission of any falsified documents or information to the ABS; or</p>
							<p><nbsp/> <nbsp/>b. the use of any falsified ABS documents or the submission of any such documents to other persons; or</p>
							<p><nbsp/> <nbsp/>c. the giving or receiving of aid in the examination as evidenced either by observation at the time of the examination or by analysis of my answers and those or one or more other participants in that examination; or</p>
							<p><nbsp/> <nbsp/>d. the unauthorized possession, reproduction, or disclosure of any material, including but not limited to examination questions or answers before, during, or after the examination; or</p>
							<p><nbsp/> <nbsp/>e. the offer of any financial or other benefit to any director, officer, employee, proctor, or other agent or representative of the ABS in return for any right, privilege or benefit which is not usually granted by the ABS to other similarly situated candidates or persons,</p>
						</p>
					may be sufficient cause for the ABS to bar me permanently from all future examinations, to terminate my participation in the examination, to invalidate the results of my examination, to withhold my scores or certificate, to revoke my certificate, or to take other appropriate action.</li>
					<li>I hereby authorize any hospital or medical staff where I now have, have had, or have applied for medical staff privileges, and any medical organization of which I am a member or to which I have applied for membership, and any person who may have information (including medical records, patient records, and reports of committees) which is deemed by ABS to be material to its evaluation of this application, to provide such information to representatives of the ABS.  I agree that communications of any nature made to the ABS regarding this application may be made in confidence and shall not be made available to me under any circumstances.  I hereby release from liability any hospital, medical staff, medical organization or person, and ABS and its representatives, for acts performed in connection with this application.</li>
					<li>I hereby agree to indemnify ABS, its members, examiners, officers, employees, or other agents or representatives, or any  hospital, medical staff, medical organization or person that provides information pursuant to this application and hold them harmless from any and all claims, losses, liabilities, expenses, lawsuits and damages (including attorneys'' fees, costs and expenses) arising out of any action the ABS or any of its agents or representatives may take in regard to this application.</li>
					<li>I hereby consent to submit to the exclusive jurisdiction of the courts of Philadelphia County, Pennsylvania for any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification, and agree not to commence any action, suit or proceeding relating thereto except in such courts.  I hereby agree that any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification shall be governed by the laws of the Commonwealth of Pennsylvania.</li>
					<li>I understand my certificate will be valid on the condition that I meet the requirements of the ABS Continuous Certification Program, which may be modified at the sole discretion of the ABS, and which include successful completion of periodic assessments, as well as participation in continuing medical education and practice improvement activities. I recognize that not meeting these requirements at any time may result in the public reporting of my failure to meet current ABS Continuous Certification requirements and may also result in suspension or revocation  of my certificate.</li>
					<li>I understand and agree that if I am certified, the ABS will send biographical and demographic data about me to the American Board of Medical Specialties (ABMS), which will contact me directly regarding the publication of my information in the ABMS Directory of Board Certified Medical Specialists.</li>
					<li>I understand and agree that the ABS may inform the director of the program in which I complete my chief resident year or other special requirements of the ABS as to my performance on any or all of the ABS'' examinations taken by me up to the point of certification.</li>
					<li>I understand and agree that the ABS, given its obligation to the public, may disclose to third parties, including medical licensing authorities, otherwise confidential information about me whenever in its sole judgment it has determined my conduct to be unethical or unprofessional.</li>
					<li>I consent and give permission to the ABS to use in de-identified format any data I submit as part of the ABS examination process (including data derived from my application, practice profile or examination results) for evaluation and research purposes authorized by the ABS.</li>
					<li>I am in good ethical standing in my community. I hereby pledge myself to the highest standards in the practice of surgery. If I am certified and these statements are shown to be false, I agree to surrender my certificate.</li>
				</ol>',6,6),
        (5,3,'	<p>Carefully review the <bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold> below.  Check the box that appears beneath your name if you agree with each of the statements.  This will serve as your electronic signature.</p>
		<p>Your Program Director will be contacted separately to attest to your clinical skills.  Approval of your application is contingent upon receipt of your program director''s attestation.</p>
		<p>Exam registration may be permitted pending the formal ABS review and approval of your electronically submitted application materials. The ABS reserves the right to cancel your registration and your scheduled examination center appointment should your submitted application materials not meet application requirements.</p>
		<br/>
		<p><bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold></p>
				<ol>
					<li>I hereby make request to The American Board of Surgery, Inc. (ABS) to enter the evaluation and examination process leading to certification or Continuous Certification in surgery, vascular surgery, pediatric surgery, surgical critical care, complex general surgical oncology, or surgery of the hand, as applicable, all in accordance with and subject to ABS bylaws and policies.  I agree that in this process the ABS may investigate my surgical performance, knowledge, professionalism, and my standing and reputation as a physician, including my compliance with the standards and ethics of the profession.  I understand and agree that:
						<p>
							<p><nbsp/> <nbsp/>a. the submission of any falsified documents or information to the ABS; or</p>
							<p><nbsp/> <nbsp/>b. the use of any falsified ABS documents or the submission of any such documents to other persons; or</p>
							<p><nbsp/> <nbsp/>c. the giving or receiving of aid in the examination as evidenced either by observation at the time of the examination or by analysis of my answers and those or one or more other participants in that examination; or</p>
							<p><nbsp/> <nbsp/>d. the unauthorized possession, reproduction, or disclosure of any material, including but not limited to examination questions or answers before, during, or after the examination; or</p>
							<p><nbsp/> <nbsp/>e. the offer of any financial or other benefit to any director, officer, employee, proctor, or other agent or representative of the ABS in return for any right, privilege or benefit which is not usually granted by the ABS to other similarly situated candidates or persons,</p>
						</p>
					may be sufficient cause for the ABS to bar me permanently from all future examinations, to terminate my participation in the examination, to invalidate the results of my examination, to withhold my scores or certificate, to revoke my certificate, or to take other appropriate action.</li>
					<li>I hereby authorize any hospital or medical staff where I now have, have had, or have applied for medical staff privileges, and any medical organization of which I am a member or to which I have applied for membership, and any person who may have information (including medical records, patient records, and reports of committees) which is deemed by ABS to be material to its evaluation of this application, to provide such information to representatives of the ABS.  I agree that communications of any nature made to the ABS regarding this application may be made in confidence and shall not be made available to me under any circumstances.  I hereby release from liability any hospital, medical staff, medical organization or person, and ABS and its representatives, for acts performed in connection with this application.</li>
					<li>I hereby agree to indemnify ABS, its members, examiners, officers, employees, or other agents or representatives, or any  hospital, medical staff, medical organization or person that provides information pursuant to this application and hold them harmless from any and all claims, losses, liabilities, expenses, lawsuits and damages (including attorneys'' fees, costs and expenses) arising out of any action the ABS or any of its agents or representatives may take in regard to this application.</li>
					<li>I hereby consent to submit to the exclusive jurisdiction of the courts of Philadelphia County, Pennsylvania for any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification, and agree not to commence any action, suit or proceeding relating thereto except in such courts.  I hereby agree that any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification shall be governed by the laws of the Commonwealth of Pennsylvania.</li>
					<li>I understand my certificate will be valid on the condition that I meet the requirements of the ABS Continuous Certification Program, which may be modified at the sole discretion of the ABS, and which include successful completion of periodic assessments, as well as participation in continuing medical education and practice improvement activities. I recognize that not meeting these requirements at any time may result in the public reporting of my failure to meet current ABS Continuous Certification requirements and may also result in suspension or revocation  of my certificate.</li>
					<li>I understand and agree that if I am certified, the ABS will send biographical and demographic data about me to the American Board of Medical Specialties (ABMS), which will contact me directly regarding the publication of my information in the ABMS Directory of Board Certified Medical Specialists.</li>
					<li>I understand and agree that the ABS may inform the director of the program in which I complete my chief resident year or other special requirements of the ABS as to my performance on any or all of the ABS'' examinations taken by me up to the point of certification.</li>
					<li>I understand and agree that the ABS, given its obligation to the public, may disclose to third parties, including medical licensing authorities, otherwise confidential information about me whenever in its sole judgment it has determined my conduct to be unethical or unprofessional.</li>
					<li>I consent and give permission to the ABS to use in de-identified format any data I submit as part of the ABS examination process (including data derived from my application, practice profile or examination results) for evaluation and research purposes authorized by the ABS.</li>
					<li>I am in good ethical standing in my community. I hereby pledge myself to the highest standards in the practice of surgery. If I am certified and these statements are shown to be false, I agree to surrender my certificate.</li>
				</ol>',6,6),
        (5,5,'	<p>Carefully review the <bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold> below.  Check the box that appears beneath your name if you agree with each of the statements.  This will serve as your electronic signature.</p>
		<p>Exam registration may be permitted pending the formal ABS review and approval of your electronically submitted application materials. The ABS reserves the right to cancel your registration and your scheduled examination center appointment should your submitted application materials not meet application requirements.</p>
		<p>Your Program Director will be contacted separately to attest to your clinical skills.  Approval of your application is contingent upon receipt of your program director''s attestation.</p>
		<br/>
		<p><bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold></p>
				<ol>
					<li>I hereby make request to The American Board of Surgery, Inc. (ABS) to enter the evaluation and examination process leading to certification or Continuous Certification in surgery, vascular surgery, pediatric surgery, surgical critical care, complex general surgical oncology, or surgery of the hand, as applicable, all in accordance with and subject to ABS bylaws and policies.  I agree that in this process the ABS may investigate my surgical performance, knowledge, professionalism, and my standing and reputation as a physician, including my compliance with the standards and ethics of the profession.  I understand and agree that:
						<p>
							<p><nbsp/> <nbsp/>a. the submission of any falsified documents or information to the ABS; or</p>
							<p><nbsp/> <nbsp/>b. the use of any falsified ABS documents or the submission of any such documents to other persons; or</p>
							<p><nbsp/> <nbsp/>c. the giving or receiving of aid in the examination as evidenced either by observation at the time of the examination or by analysis of my answers and those or one or more other participants in that examination; or</p>
							<p><nbsp/> <nbsp/>d. the unauthorized possession, reproduction, or disclosure of any material, including but not limited to examination questions or answers before, during, or after the examination; or</p>
							<p><nbsp/> <nbsp/>e. the offer of any financial or other benefit to any director, officer, employee, proctor, or other agent or representative of the ABS in return for any right, privilege or benefit which is not usually granted by the ABS to other similarly situated candidates or persons,</p>
						</p>
					may be sufficient cause for the ABS to bar me permanently from all future examinations, to terminate my participation in the examination, to invalidate the results of my examination, to withhold my scores or certificate, to revoke my certificate, or to take other appropriate action.</li>
					<li>I hereby authorize any hospital or medical staff where I now have, have had, or have applied for medical staff privileges, and any medical organization of which I am a member or to which I have applied for membership, and any person who may have information (including medical records, patient records, and reports of committees) which is deemed by ABS to be material to its evaluation of this application, to provide such information to representatives of the ABS.  I agree that communications of any nature made to the ABS regarding this application may be made in confidence and shall not be made available to me under any circumstances.  I hereby release from liability any hospital, medical staff, medical organization or person, and ABS and its representatives, for acts performed in connection with this application.</li>
					<li>I hereby agree to indemnify ABS, its members, examiners, officers, employees, or other agents or representatives, or any  hospital, medical staff, medical organization or person that provides information pursuant to this application and hold them harmless from any and all claims, losses, liabilities, expenses, lawsuits and damages (including attorneys'' fees, costs and expenses) arising out of any action the ABS or any of its agents or representatives may take in regard to this application.</li>
					<li>I hereby consent to submit to the exclusive jurisdiction of the courts of Philadelphia County, Pennsylvania for any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification, and agree not to commence any action, suit or proceeding relating thereto except in such courts.  I hereby agree that any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification shall be governed by the laws of the Commonwealth of Pennsylvania.</li>
					<li>I understand my certificate will be valid on the condition that I meet the requirements of the ABS Continuous Certification Program, which may be modified at the sole discretion of the ABS, and which include successful completion of periodic assessments, as well as participation in continuing medical education and practice improvement activities. I recognize that not meeting these requirements at any time may result in the public reporting of my failure to meet current ABS Continuous Certification requirements and may also result in suspension or revocation  of my certificate.</li>
					<li>I understand and agree that if I am certified, the ABS will send biographical and demographic data about me to the American Board of Medical Specialties (ABMS), which will contact me directly regarding the publication of my information in the ABMS Directory of Board Certified Medical Specialists.</li>
					<li>I understand and agree that the ABS may inform the director of the program in which I complete my chief resident year or other special requirements of the ABS as to my performance on any or all of the ABS'' examinations taken by me up to the point of certification.</li>
					<li>I understand and agree that the ABS, given its obligation to the public, may disclose to third parties, including medical licensing authorities, otherwise confidential information about me whenever in its sole judgment it has determined my conduct to be unethical or unprofessional.</li>
					<li>I consent and give permission to the ABS to use in de-identified format any data I submit as part of the ABS examination process (including data derived from my application, practice profile or examination results) for evaluation and research purposes authorized by the ABS.</li>
					<li>I am in good ethical standing in my community. I hereby pledge myself to the highest standards in the practice of surgery. If I am certified and these statements are shown to be false, I agree to surrender my certificate.</li>
				</ol>',6,6),
        (5,6,'	<p>Carefully review the <bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold> below.  Check the box that appears beneath your name if you agree with each of the statements.  This will serve as your electronic signature.</p>
	<p>Exam registration may be permitted pending the formal ABS review and approval of your electronically submitted application materials. The ABS reserves the right to cancel your registration and your scheduled examination center appointment should your submitted application materials not meet application requirements.</p>
	<p>Your Program Director will be contacted separately to attest to your clinical skills.  Approval of your application is contingent upon receipt of your program director''s attestation.</p>
		<br/>
		<p><bold>Surgeon Agreement Regarding ABS Certification/Continuous Certification Process</bold></p>
				<ol>
					<li>I hereby make request to The American Board of Surgery, Inc. (ABS) to enter the evaluation and examination process leading to certification or Continuous Certification in surgery, vascular surgery, pediatric surgery, surgical critical care, complex general surgical oncology, or surgery of the hand, as applicable, all in accordance with and subject to ABS bylaws and policies.  I agree that in this process the ABS may investigate my surgical performance, knowledge, professionalism, and my standing and reputation as a physician, including my compliance with the standards and ethics of the profession.  I understand and agree that:
						<p>
							<p><nbsp/> <nbsp/>a. the submission of any falsified documents or information to the ABS; or</p>
							<p><nbsp/> <nbsp/>b. the use of any falsified ABS documents or the submission of any such documents to other persons; or</p>
							<p><nbsp/> <nbsp/>c. the giving or receiving of aid in the examination as evidenced either by observation at the time of the examination or by analysis of my answers and those or one or more other participants in that examination; or</p>
							<p><nbsp/> <nbsp/>d. the unauthorized possession, reproduction, or disclosure of any material, including but not limited to examination questions or answers before, during, or after the examination; or</p>
							<p><nbsp/> <nbsp/>e. the offer of any financial or other benefit to any director, officer, employee, proctor, or other agent or representative of the ABS in return for any right, privilege or benefit which is not usually granted by the ABS to other similarly situated candidates or persons,</p>
						</p>
					may be sufficient cause for the ABS to bar me permanently from all future examinations, to terminate my participation in the examination, to invalidate the results of my examination, to withhold my scores or certificate, to revoke my certificate, or to take other appropriate action.</li>
					<li>I hereby authorize any hospital or medical staff where I now have, have had, or have applied for medical staff privileges, and any medical organization of which I am a member or to which I have applied for membership, and any person who may have information (including medical records, patient records, and reports of committees) which is deemed by ABS to be material to its evaluation of this application, to provide such information to representatives of the ABS.  I agree that communications of any nature made to the ABS regarding this application may be made in confidence and shall not be made available to me under any circumstances.  I hereby release from liability any hospital, medical staff, medical organization or person, and ABS and its representatives, for acts performed in connection with this application.</li>
					<li>I hereby agree to indemnify ABS, its members, examiners, officers, employees, or other agents or representatives, or any  hospital, medical staff, medical organization or person that provides information pursuant to this application and hold them harmless from any and all claims, losses, liabilities, expenses, lawsuits and damages (including attorneys'' fees, costs and expenses) arising out of any action the ABS or any of its agents or representatives may take in regard to this application.</li>
					<li>I hereby consent to submit to the exclusive jurisdiction of the courts of Philadelphia County, Pennsylvania for any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification, and agree not to commence any action, suit or proceeding relating thereto except in such courts.  I hereby agree that any actions, suits or proceedings arising out of or relating to this application, the grading or conduct of my examinations, and/or the failure of the ABS to issue me a Certificate of Qualification shall be governed by the laws of the Commonwealth of Pennsylvania.</li>
					<li>I understand my certificate will be valid on the condition that I meet the requirements of the ABS Continuous Certification Program, which may be modified at the sole discretion of the ABS, and which include successful completion of periodic assessments, as well as participation in continuing medical education and practice improvement activities. I recognize that not meeting these requirements at any time may result in the public reporting of my failure to meet current ABS Continuous Certification requirements and may also result in suspension or revocation  of my certificate.</li>
					<li>I understand and agree that if I am certified, the ABS will send biographical and demographic data about me to the American Board of Medical Specialties (ABMS), which will contact me directly regarding the publication of my information in the ABMS Directory of Board Certified Medical Specialists.</li>
					<li>I understand and agree that the ABS may inform the director of the program in which I complete my chief resident year or other special requirements of the ABS as to my performance on any or all of the ABS'' examinations taken by me up to the point of certification.</li>
					<li>I understand and agree that the ABS, given its obligation to the public, may disclose to third parties, including medical licensing authorities, otherwise confidential information about me whenever in its sole judgment it has determined my conduct to be unethical or unprofessional.</li>
					<li>I consent and give permission to the ABS to use in de-identified format any data I submit as part of the ABS examination process (including data derived from my application, practice profile or examination results) for evaluation and research purposes authorized by the ABS.</li>
					<li>I am in good ethical standing in my community. I hereby pledge myself to the highest standards in the practice of surgery. If I am certified and these statements are shown to be false, I agree to surrender my certificate.</li>
				</ol>',6,6)