/**
#############################################################################
WARNING GENERATED CODE DO NOT MODIFY - 

All client side API services are generated by the server side API 
developer when the API is created. Please do not make changes to this file

############################################################################
**/
export interface ICertificationReadOnlyModel {
    speciality: string;
    certificateId: string;
    initialCertificationDate: string;
    endDateDisplay: string;
}
