import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';

import { IUserCredentialModel } from '../../models/users/user-credential.model';

/**
#############################################################################
WARNING GENERATED CODE DO NOT MODIFY - 

All client side API services are generated by the server side API 
developer when the API is created. Please do not make changes to this file

############################################################################
**/

@Injectable({
  providedIn: 'root',
})
export class UserCredentialsService {
    private readonly baseEndpoint = 'users/credentials';

    constructor(private httpClient: HttpClient) {}

 
        public retrieveUserCredential_GetByUserId(apiVersion = '1.0'): Observable<IUserCredentialModel> {
            /**
            * Claims
            */
            
            /**
            * Business Rules
            * Business rules for property: EmailAddress
            *   Rule Name: RegEx
            *   Rule Value: YtgIm.Library.Rules.RuleOptions
            * Business rules for property: Password
            *   Rule Name: RegEx
            *   Rule Value: YtgIm.Library.Rules.RuleOptions
            */
            
            /**
            * Required Parameters
            * apiVersion
            */
            
            /**
            * Calls Sp(s)
            * [get_user_account]
            */
            
            
            return this.httpClient.get<IUserCredentialModel>(`${this.baseEndpoint}/by-userid?api-version=${apiVersion}`);
        }
 
        public updateUserCredential(model: IUserCredentialModel,
        apiVersion = '1.0') : Observable<IUserCredentialModel> {
            /**
            * Claims
            */
            
            /**
            * Business Rules
            * Business rules for property: EmailAddress
            *   Rule Name: RegEx
            *   Rule Value: YtgIm.Library.Rules.RuleOptions
            * Business rules for property: Password
            *   Rule Name: RegEx
            *   Rule Value: YtgIm.Library.Rules.RuleOptions
            */
            
            /**
            * Required Parameters
            * emailAddress:String
            * password:String
            * apiVersion
            */
            
            /**
            * Calls Sp(s)
            * [upd_user_account]
            */
            
            
            //TODO - Fix this PUT implementation when we fix the PUT calls in the YTG-ANGULAR package
            return this.httpClient.put<IUserCredentialModel>(`${this.baseEndpoint}?api-version=${apiVersion}`,
            model);
        }


}
