import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';

import { IAdditionalTrainingModel } from '../../../models/examinations/gq/additional-training.model';
import { IAdditionalTrainingReadOnlyModel } from '../../../models/examinations/gq/additional-training-read-only.model';

/**
#############################################################################
WARNING GENERATED CODE DO NOT MODIFY - 

All client side API services are generated by the server side API 
developer when the API is created. Please do not make changes to this file

############################################################################
**/

@Injectable({
  providedIn: 'root',
})
export class AdditionalTrainingsService {
    private readonly baseEndpoint = 'api/examinations/gq/additional-trainings';

    constructor(private httpClient: HttpClient) {}

 
        public retrieveAdditionalTraining_GetByTrainingId(trainingId: number,
        apiVersion = '1.0'): Observable<IAdditionalTrainingModel> {
            /**
            * Claims
            */
            
            /**
            * Business Rules
            * No business rules exist for this model
            */
            
            /**
            * Required Parameters
            * trainingId:Number
            * apiVersion
            */
            
            /**
            * Calls Sp(s)
            * [get_additionaltraining_bytrainingid]
            */
            
            
            return this.httpClient.get<IAdditionalTrainingModel>(`${this.baseEndpoint}/?api-version=${apiVersion}&trainingId=${trainingId}`);
        }
 
        public createAdditionalTraining(model: IAdditionalTrainingModel, 
            apiVersion = '1.0'): Observable<IAdditionalTrainingModel> {
            /**
            * Claims
            */
            
            /**
            * Business Rules
            * No business rules exist for this model
            */
            
            /**
            * Required Parameters
            * dateEnded:Date
            * dateStarted:Date
            * other:String
            * institutionId:Number
            * city:String
            * stateId:String
            * typeOfTraining:String
            * apiVersion
            */
            
            /**
            * Calls Sp(s)
            * [ins_additionaltraining_bytrainingid]
            */
            
            
            return this.httpClient.post<IAdditionalTrainingModel>(`${this.baseEndpoint}/?api-version=${apiVersion}`, 
                model);
        }
 
        public updateAdditionalTraining(trainingId: number,
        model: IAdditionalTrainingModel,
        apiVersion = '1.0') : Observable<IAdditionalTrainingModel> {
            /**
            * Claims
            */
            
            /**
            * Business Rules
            * No business rules exist for this model
            */
            
            /**
            * Required Parameters
            * trainingId:Number
            * dateEnded:Date
            * dateStarted:Date
            * other:String
            * institutionId:Number
            * city:String
            * stateId:String
            * typeOfTraining:String
            * apiVersion
            */
            
            /**
            * Calls Sp(s)
            * [update_additionaltraining_bytrainingid]
            */
            
            
            
            return this.httpClient.put<IAdditionalTrainingModel>(`${this.baseEndpoint}?api-version=${apiVersion}&trainingId=${trainingId}`,
            model);
        }
 
        public retrieveAdditionalTrainingReadOnly_GetAllByUserId(userId: number,
        apiVersion = '1.0'): Observable<IAdditionalTrainingReadOnlyModel[]> {
            /**
            * Claims
            */
            
            /**
            * Business Rules
            * No business rules exist for this model
            */
            
            /**
            * Required Parameters
            * userId:Number
            * apiVersion
            */
            
            /**
            * Calls Sp(s)
            * [get_additionaltrainingreadonly_allbyuserid]
            */
            
            
            return this.httpClient.get<IAdditionalTrainingReadOnlyModel[]>(`${this.baseEndpoint}/all?api-version=${apiVersion}&userId=${userId}`);
        }


}
