/**
#############################################################################
WARNING GENERATED CODE DO NOT MODIFY - 

All client side API services are generated by the server side API 
developer when the API is created. Please do not make changes to this file

############################################################################
**/
export interface IAdditionalTrainingReadOnlyModel {
    trainingId: number;
    typeOfTraining: string;
    state: string;
    city: string;
    institutionName: string;
    other: string;
    dateStarted: Date;
    dateEnded: Date;
}
